language: minimal
script:
    - script/build.sh
deploy:
    - provider: releases
      api_key:
          secure: "S2eorGb+zSwOtcZK5dzHTHrjJocSl5iv/xia6dz7f4iBBFCs2Qbz9VfR4gsYWHSaiGBS4NnksJsLURYOd9wDP1vS+IrwNjQiP/ehaiUFPndTBrlawlD93DqjcO1kYu3e+PHE4GfjrNkS4ghhUNM6E0UJtBzz+F/AnpTimMGHecaQ5a0K5J3JlbX8GUNeitOuwGlS6FYddrVvRVv9g3h/6chQR4KvJmkgP7Nsw8WKE/EeaUycXCwPt+1LPjQSwvc+qIL6Z56o9Fc7aig78MjTf8PaGCYWHigAhy0nLEz2Dvsa318MCPmVsA75gy6YtYE6Zcv0atqS9Cbq4AEx0rat+q+BVZoKCRsDUBS4dvXzyyRjbmIKg/YrPNLl9bEKwK7qen7d10xzwIITEzx+E1UXhMzvumYWMrgOUi3LfoWU2AJLWxUpeREnyJD6PWHUKOx4eM7yJhqs8XQxmOcATWDZmvwqdAhzSij91FDXJJEC9R61xsfW54Aa/3ZmiW14wNBSQcjJe6jNcV3v7ioOxtp3CfSxs1FUAwm7GbcBfWZH2dyfVQKjm/l+bnerdupMxNlgz7DNS4QIDkTJmK0MVzG4Sw5xQOkk97vJSArPlRGd2DtNSocB/+qaocjDu1N1SbArp6hJm2P43vMzowRF7VxvJ3LBW/0VNfiNTZr+B2PeIfk="
      file: dist/rules.txt
      skip_cleanup: true
      on:
          tags: true
